resolves #1add typing of boticot and messenger responses
Boticot/boticot-messenger-connector pull request #2
Opened 2022-09-22 13:53 UTC by leooel88

Add typings boticot and messenger typings

2022-09-27 09:05 UTC, omar-mellouli requested changes

2022-09-27 09:05 UTC, omar-mellouli commented on src/client/nlu.ts
> +const tunnel = require('tunnel'); //
to remove

2022-09-27 09:05 UTC, omar-mellouli commented on package.json
> +    "tunnel": "^0.0.6",
to remove

2022-09-27 09:05 UTC, omar-mellouli commented on src/client/nlu.ts
> +
to remove

2022-09-27 09:05 UTC, omar-mellouli commented on src/express.ts
> -    public appExpress: Application;
rollback refactoring

2022-09-27 09:05 UTC, omar-mellouli commented on typings/global.d.ts
> +	postback: Webhook // BIZARRE
remove comment

2022-09-27 09:05 UTC, omar-mellouli commented on typings/global.d.ts
> +export class ImageLoadResponse {
to remove

2022-09-27 09:05 UTC, omar-mellouli commented on typings/global.d.ts
> +export class ImageLoadData {
to remove

2022-09-27 09:05 UTC, omar-mellouli commented on typings/express.d.ts
> +declare namespace Express {
check if mandatory

2022-09-27 09:05 UTC, omar-mellouli commented on tsconfig.json
> +    "skipLibCheck": true,
check if needed

2022-09-27 09:05 UTC, omar-mellouli commented on src/utils/messenger.ts
> +	MessengerTextImageAndSuggestion,
to remove

2022-09-27 09:05 UTC, omar-mellouli commented on src/services/messenger.ts
> +    async handleQuickReplies(sender_psid: string, received_message: Message) {
rollback

2022-09-27 09:05 UTC, omar-mellouli commented on src/services/messenger.ts
> +
remove

2022-09-27 09:05 UTC, omar-mellouli commented on typings/global.d.ts
> +export class Recipient {
remove class (for all)

2022-09-27 09:05 UTC, omar-mellouli commented on typings/global.d.ts
> +export interface MessengerTextImageAndSuggestion extends MessengerRequestBasic {
remove duplicated

2022-09-27 09:05 UTC, omar-mellouli commented on environment.d.ts
> +declare global {
to remove

2022-09-27 09:05 UTC, omar-mellouli commented on package.json
> +    "dotenv": "^16.0.2",
to remove

2022-09-27 09:05 UTC, omar-mellouli commented
rename commit message

2022-09-27 14:03 UTC, omar-mellouli commented
please squash commit

2022-10-05 11:08 UTC, omar-mellouli commented on src/server.ts
> +import 'dotenv/config'
always needed ?

2022-10-05 11:08 UTC, omar-mellouli commented on src/services/messenger.ts
> +            console.error('Error when handling entry ', error)
why remove use of Template strings ?

2022-10-05 11:08 UTC, omar-mellouli commented on src/services/messenger.ts
> +            console.error('Error when handling message', error)
why remove use of Template strings ?

2022-10-05 11:08 UTC, omar-mellouli commented on src/services/messenger.ts
> +			const message = await this.buildMessages(sender_psid, boticot_data)
remove extra space or rollback

2022-10-05 13:12 UTC, leooel88 commented on src/client/nlu.ts
> +const tunnel = require('tunnel'); //
DONE

2022-10-05 13:13 UTC, leooel88 commented on package.json
> +    "tunnel": "^0.0.6",
DONE

2022-10-05 13:23 UTC, leooel88 commented on typings/global.d.ts
> +	postback: Webhook // BIZARRE
DONE

2022-10-05 13:23 UTC, leooel88 commented on typings/global.d.ts
> +export class ImageLoadResponse {
DONE

2022-10-05 13:23 UTC, leooel88 commented on typings/global.d.ts
> +export class ImageLoadData {
DONE

2022-10-05 13:25 UTC, leooel88 commented on src/utils/messenger.ts
> +	MessengerTextImageAndSuggestion,
DONE

2022-10-05 13:26 UTC, leooel88 commented on src/services/messenger.ts
> +    async handleQuickReplies(sender_psid: string, received_message: Message) {
DONE

2022-10-05 13:27 UTC, leooel88 commented on src/services/messenger.ts
> +
DONE

2022-10-05 13:27 UTC, leooel88 commented on typings/global.d.ts
> +export class Recipient {
DONE

2022-10-05 13:28 UTC, leooel88 commented on typings/global.d.ts
> +export interface MessengerTextImageAndSuggestion extends MessengerRequestBasic {
DONE

2022-10-05 13:29 UTC, leooel88 commented on environment.d.ts
> +declare global {
DONE

2022-10-05 13:29 UTC, leooel88 commented on package.json
> +    "dotenv": "^16.0.2",
DONE

2022-10-05 15:34 UTC, leooel88 commented on src/client/nlu.ts
> +
DONE

2022-10-05 15:35 UTC, leooel88 commented on src/express.ts
> -    public appExpress: Application;
When pushing, tabs are added automaticaly
On local code, normal tabs (like master branch)

2022-10-05 15:37 UTC, leooel88 commented on typings/express.d.ts
> +declare namespace Express {
DONE

2022-10-05 15:37 UTC, leooel88 commented on tsconfig.json
> +    "skipLibCheck": true,
skipLibCheck needed

2022-10-05 15:40 UTC, leooel88 commented on src/services/messenger.ts
> +			const message = await this.buildMessages(sender_psid, boticot_data)
When pushing, tabs are added automaticaly
On local code, normal indentation

2022-10-06 11:01 UTC, leooel88 commented on src/services/messenger.ts
> +            console.error('Error when handling message', error)
DONE : Template string back

2022-10-06 11:01 UTC, leooel88 commented on src/services/messenger.ts
> +            console.error('Error when handling entry ', error)
DONE : Template string back

2022-10-06 11:02 UTC, leooel88 commented on src/server.ts
> +import 'dotenv/config'
DONE : removed

2022-10-06 11:02 UTC, omar-mellouli requested changes

2022-10-06 11:02 UTC, omar-mellouli commented on src/routes/messenger.ts
> +router.get('/webhook', (req: WebhookVerificationRequest, res: Response): void =>
Check if Ok when authorize webhook and when send message

2022-10-06 11:02 UTC, omar-mellouli commented on src/services/messenger.ts
> +            console.error('Error when handling intent', error)
why remove use of Template strings ?

2022-10-06 11:03 UTC, leooel88 commented on src/routes/messenger.ts
> +router.get('/webhook', (req: WebhookVerificationRequest, res: Response): void =>
DONE : works with void

2022-10-06 11:03 UTC, leooel88 commented on src/services/messenger.ts
> +            console.error('Error when handling intent', error)
DONE : Template strings back

2022-10-06 11:30 UTC, omar-mellouli approved these changes

2022-10-06 11:33 UTC, merged